version: '3.1'
services:
  flaskapp:
    container_name: flaskapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    tty: true
    restart: unless-stopped
  psql:
    container_name: psql
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    restart: unless-stopped